# Generated by Django 4.2.7 on 2023-11-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
    ]
