# Generated by Django 4.2.7 on 2023-11-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
