# Generated by Django 4.2.7 on 2023-11-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
